import Head from "next/head";
import Inicio from "./components/Inicio";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Inicio />
      </main>
    </div>
  );
}
