import Head from "next/head";
import Inicio from "./components/Inicio";
import Parte02 from "./components/Parte02";
import Parte03 from "./components/Parte03";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Inicio />
        <Parte02 />
        <Parte03 />
      </main>
    </div>
  );
}
